### ISSUE TITLE
Якщо для України тоді де український інтерфейс?

### ISSUE THREAD

**Issue by typo3ua** [leon-mbs/zippyerp#6]
Привіт! 

Випадково натрапив на ваш проект у мережі. 

Зацікавили лише те що для України але коли більше заглибився то не побачив нічого українського.

Якщо для України тоді де український інтерфейс?

Заздалегідь, дякую.

**Comment by leon-mbs** [comment]
Для України тому  що  заточена  на  українське законодавство та  Українськи ринок.
Чому  всі  вимагають у  опенсорс  проекту  українсько мови  а  в  той же  час  користуются платною російською одноце
Взагалі то  український інтерфес був але  я  вирішив уніфікувати  зі складським варіантом так  простіше супроводжувати.
коли буде  попит на програму або хтось задонатить  тоді  і переведу знов.  
Поки що ті хто впровадив програму  захотіли саме  російський.
